# Generated by Django 5.0 on 2024-08-30 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('nascimento', models.DateField(verbose_name='Nascimento')),
                ('cpf', models.CharField(max_length=11, verbose_name='Numero do CPF')),
            ],
        ),
        migrations.CreateModel(
            name='Passaporte',
            fields=[
                ('numero', models.CharField(max_length=100, verbose_name='numero')),
                ('data_criacao', models.DateField(verbose_name='data criacao')),
                ('validade', models.DateField(verbose_name='validade')),
                ('dono', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aula.pessoa')),
            ],
        ),
    ]
